# Generated by Django 5.1.6 on 2025-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("revenue", models.FloatField(default=0.0)),
                ("profit", models.FloatField(default=0.0)),
                ("employees", models.IntegerField(default=0)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
    ]
